### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by Abraarkhan** [Abraarkhan/Java_Algorithms#31]
You can edit the current format, or you can make a new readme file with good explanatory content and visual appeal.

**Comment by NEHA-MERIYA** [comment]
Updated readme
please review and accept my PR for Hacktoberfest2021

**Comment by Abraarkhan** [comment]
You don't have to wait for me to assign you the role, You can put a PR and I will review @suman-somu

**Comment by suman-somu** [comment]
Yeah, okay .
But for this issue, has been fixed by a pr of mine .
