### ISSUE TITLE
Need solution in JAVA to make a virtual piggy bank

### ISSUE THREAD

**Issue by Abraarkhan** [Abraarkhan/Java_Algorithms#68]
The java application should be able to calculate the bank balance and dynamic transactions. Interest addition and insurance premium deduction.

**Comment by tripathisharad** [comment]
Hi @Abraarkhan I would like contribute in this as I am a java developer so can you assign me this ?

**Comment by Shubhgajj2004** [comment]
Hi @Abraarkhan I would also like to contribute.

**Comment by Abraarkhan** [comment]
Heyy user @tripathisharad I have assigned the issue to you. Please make a new folder for your submission.

**Comment by tripathisharad** [comment]
Hello @Abraarkhan I have created a .class file of piggy bank please check it out
